version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: authpass
    ports: ["5433:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports: ["8000:8000"]
    depends_on:
      - db
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: authpass
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: "True"

volumes:
  postgres_data:
